[pytest]
asyncio_mode = strict
asyncio_default_fixture_loop_scope = function
filterwarnings =
    ignore:.*PendingDeprecationWarning.*
    ignore:.*default fixture loop scope.*:pytest.PytestDeprecationWarning
testpaths = tests
